### ISSUE TITLE
.readme file required

### ISSUE THREAD

**Issue by mehta-raghav** [mehta-raghav/Rake-Bot#1]
I'd like one of my university projects to have a .readme file.
You can fine pypi style guide here: https://packaging.python.org/guides/making-a-pypi-friendly-readme

This makes for a good first pull request for people doing Hacktoberfest.
Thanks and happy open source coding.

**Comment by SarthakRana** [comment]
Hi. I would like to work on this issue. Please assign it to me.

**Comment by DevanshD3** [comment]
Hi I would like to work on it please

**Comment by mehta-raghav** [comment]
Hi @DevanshD3 think it would be fair to give this to @SarthakRana on a first come first serve basis. Thanks for considering. I'll see if I can create another issue for you on my other projects.

**Comment by DevanshD3** [comment]
Yeah sure! Thanks a lot
